In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('/content/KaggleV2-May-2016.csv')

In [11]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [12]:
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [13]:
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

In [14]:
df['WaitTime'] = (
    df['AppointmentDay'] - df['ScheduledDay']
).dt.days

In [15]:
df = df[df['WaitTime'] >= 0]

In [16]:
df['No-show'] = df['No-show'].map({
    'No': 0,
    'Yes': 1
})

In [17]:
df.to_csv('cleaned_data.csv', index=False)

In [18]:
df.columns = df.columns.str.replace('-', '_')

In [19]:
df.to_csv('cleaned_data.csv', index=False)

In [20]:
features = [
    'Age',
    'Scholarship',
    'Hipertension',
    'Diabetes',
    'Alcoholism',
    'SMS_received',
    'WaitTime'
]

X = df[features]

y = df['No_show']

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
from sklearn.linear_model import LogisticRegression
import pandas as pd

model = LogisticRegression()

# Combine X_train and y_train to drop rows with any NaN values across both
# This ensures that features and target remain aligned after dropping NaNs.
cleaned_train_data = pd.concat([X_train, y_train], axis=1).dropna()
X_train_cleaned = cleaned_train_data[X_train.columns]
y_train_cleaned = cleaned_train_data[y_train.name]

model.fit(X_train_cleaned, y_train_cleaned)

LogisticRegression()

In [23]:
predictions = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(accuracy)

0.7152584769316287

In [25]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    predictions
)

print(cm)

[[10287    14]
 [ 4084     7]]

In [26]:
X_test['Prediction'] = predictions

X_test.to_csv(
    'predictions.csv',
    index=False
)